using System;
using System.IO;
using System.Diagnostics;
using System.Collections.Generic;

namespace BitSortCore
{
    public class CleanTarget
    {
        public string Name { get; set; } = "";
        public string PathOrKeyword { get; set; } = "";
        public string Description { get; set; } = "";
        public string Category { get; set; } = ""; // "System", "Drivers", "Dev"
        public bool Selected { get; set; } = true;
    }

    public static class BitSortEngine
    {
        public static List<CleanTarget> GetTargets()
        {
            return new List<CleanTarget>
            {
                // 1. SYSTEM JUNK
                new() { Category = "System", Name = "User Temp Files", PathOrKeyword = "USER_TEMP", Description = "Clears temporary application caches and log files from your user profile." },
                new() { Category = "System", Name = "Windows Temp Cache", PathOrKeyword = "WIN_TEMP", Description = "Clears shared system temporary folders used during software installations." },
                new() { Category = "System", Name = "System Error Logs", PathOrKeyword = "SYS_LOGS", Description = "Removes old error reports, setup logs (.log), and temporary backup files (.bak)." },

                // 2. UNIVERSAL DRIVER PURGE
                new() { Category = "Drivers", Name = "All Third-Party Drivers (Safe Scan)", PathOrKeyword = "ALL_DRIVERS", Description = "Uses Windows PnPUtil to scan and safely unregister non-system drivers (Display, Audio, Network)." },
                new() { Category = "Drivers", Name = "Leftover Installer Folders (AMD/NVIDIA)", PathOrKeyword = "DRIVER_CACHES", Description = "Deletes massive installation dump folders like C:\\AMD or C:\\NVIDIA to free up gigabytes." },

                // 3. EXTENDED IT DEV CACHES 
                new() { Category = "Dev", Name = "Java / Gradle Cache", PathOrKeyword = @".gradle\caches", Description = "Clears local build caches and dependency duplicates for Android/Java projects." },
                new() { Category = "Dev", Name = ".NET NuGet Cache", PathOrKeyword = @".nuget\packages", Description = "Cleans old versions of downloaded libraries used in C# development." },
                new() { Category = "Dev", Name = "Node.js npm Cache", PathOrKeyword = @"AppData\Local\npm-cache", Description = "Cleans global package installer cache for JavaScript environments." },
                new() { Category = "Dev", Name = "Yarn Global Cache", PathOrKeyword = @"AppData\Local\Yarn\Cache", Description = "Removes downloaded packages cache for projects using Yarn package manager." },
                new() { Category = "Dev", Name = "Python pip Cache", PathOrKeyword = @"AppData\Local\pip\cache", Description = "Deletes downloaded .whl files and source tarballs from Python package installer." },
                new() { Category = "Dev", Name = "Rust Cargo Registry", PathOrKeyword = @".cargo\registry", Description = "Clears downloaded index and source crates (libraries) for the Rust ecosystem." },
                new() { Category = "Dev", Name = "Go Build Cache", PathOrKeyword = @"AppData\Local\go-build", Description = "Wipes temporary build artifacts generated by the Go compiler (GOCACHE)." },
                new() { Category = "Dev", Name = "Docker Desktop Cache", PathOrKeyword = @"AppData\Local\Docker", Description = "Cleans local logs and temporary daemon caches for Docker containers." },
                new() { Category = "Dev", Name = "vcpkg C++ Packages", PathOrKeyword = @"AppData\Local\vcpkg\archives", Description = "Clears downloaded and archived binary packages for C/C++ development." }
            };
        }

        public static string ExecutePurge(List<CleanTarget> targets)
        {
            StringWriter log = new();
            log.WriteLine($"=== BITSORT ENGINE RUN: {DateTime.Now:HH:mm:ss} ===");
            long totalFreedBytes = 0;

            string userProfile = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);

            foreach (var target in targets)
            {
                if (!target.Selected)
                {
                    log.WriteLine($"[Skipped]: {target.Name} (User unchecked)");
                    continue;
                }

                log.WriteLine($"\n[Task]: Running {target.Name}...");

                try
                {
                    if (target.Category == "Dev")
                    {
                        string fullPath = Path.Combine(userProfile, target.PathOrKeyword);
                        totalFreedBytes += SafeDeleteFolder(fullPath);
                    }
                    else if (target.Category == "System")
                    {
                        if (target.PathOrKeyword == "USER_TEMP") totalFreedBytes += SafeDeleteFolder(Path.GetTempPath());
                        else if (target.PathOrKeyword == "WIN_TEMP") totalFreedBytes += SafeDeleteFolder(@"C:\Windows\Temp");
                        else if (target.PathOrKeyword == "SYS_LOGS")
                        {
                            totalFreedBytes += PurgeExtensionFiles(userProfile, "*.log");
                            totalFreedBytes += PurgeExtensionFiles(userProfile, "*.bak");
                        }
                    }
                    else if (target.Category == "Drivers")
                    {
                        if (target.PathOrKeyword == "DRIVER_CACHES")
                        {
                            totalFreedBytes += SafeDeleteFolder(@"C:\AMD");
                            totalFreedBytes += SafeDeleteFolder(@"C:\NVIDIA");
                            log.WriteLine("  └─ Leftover installer folders cleared.");
                        }
                        else if (target.PathOrKeyword == "ALL_DRIVERS")
                        {
                            log.WriteLine("  🚀 Scanning active Windows Driver Store...");
                            log.WriteLine(UninstallDriversViaPnpUtil());
                        }
                    }
                }
                catch (Exception ex)
                {
                    log.WriteLine($"  [!]: Error or locked: {ex.Message}");
                }
            }

            log.WriteLine($"\n🎯 PROCESS COMPLETED!");
            log.WriteLine($"💾 Total Storage Freed: {totalFreedBytes / 1024 / 1024} MB");
            return log.ToString();
        }

        private static string UninstallDriversViaPnpUtil()
        {
            StringWriter driverLog = new();
            ProcessStartInfo psi = new()
            {
                FileName = "cmd.exe", Arguments = "/c pnputil /enum-drivers",
                RedirectStandardOutput = true, UseShellExecute = false, CreateNoWindow = true
            };

            using Process? process = Process.Start(psi);
            if (process == null) return "  [Error]: Cannot access Windows PnP subsystem.";

            string output = process.StandardOutput.ReadToEnd();
            process.WaitForExit();

            using StringReader reader = new(output);
            string? line;
            string currentOemName = "";
            string currentProvider = "";
            string currentClass = "";
            int detectedCount = 0;

            driverLog.WriteLine("  --- Found Third-Party Driver Packages ---");

            while ((line = reader.ReadLine()) != null)
            {
                if (line.Contains("Published Name:")) currentOemName = line.Split(':')[1].Trim();
                else if (line.Contains("Driver Provider:")) currentProvider = line.Split(':')[1].Trim();
                else if (line.Contains("Class Name:")) currentClass = line.Split(':')[1].Trim();

                if (!string.IsNullOrEmpty(currentOemName) && !string.IsNullOrEmpty(currentProvider) && line.Trim() == "")
                {
                    bool isTargetGpu = currentProvider.ToLower().Contains("nvidia") || 
                                       ((currentProvider.ToLower().Contains("amd") || currentProvider.ToLower().Contains("advanced micro")) 
                                        && currentClass.ToLower().Contains("display"));

                    if (isTargetGpu)
                    {
                        detectedCount++;
                        driverLog.WriteLine($"    📦 Found Legacy GPU Package: {currentOemName} | Provider: {currentProvider}");
                        
                        ProcessStartInfo uninstallPsi = new()
                        {
                            FileName = "cmd.exe", Arguments = $"/c pnputil /delete-driver {currentOemName} /uninstall",
                            RedirectStandardOutput = true, UseShellExecute = false, CreateNoWindow = true
                        };
                        using Process? pUn = Process.Start(uninstallPsi);
                        pUn?.WaitForExit();
                        
                        driverLog.WriteLine($"    └─ [PnPUtil]: Safe uninstalled {currentOemName}");
                    }
                    currentOemName = ""; currentProvider = ""; currentClass = "";
                }
            }

            if (detectedCount == 0) driverLog.WriteLine("  ✅ No external GPU drivers detected. Your CPU-based graphics are untouched and safe.");
            return driverLog.ToString();
        }

        private static long SafeDeleteFolder(string path)
        {
            if (!Directory.Exists(path)) return 0;
            long bytesFreed = 0;
            try
            {
                foreach (string file in Directory.GetFiles(path, "*", SearchOption.AllDirectories))
                {
                    try { FileInfo fi = new(file); bytesFreed += fi.Length; fi.Delete(); } catch { }
                }
                foreach (string dir in Directory.GetDirectories(path))
                {
                    try { Directory.Delete(dir, true); } catch { }
                }
            }
            catch { }
            return bytesFreed;
        }

        private static long PurgeExtensionFiles(string rootPath, string extension)
        {
            long freed = 0;
            string[] safeSubFolders = { "Downloads", "AppData\\Local\\Temp" };
            foreach (var sub in safeSubFolders)
            {
                string targetPath = Path.Combine(rootPath, sub);
                if (!Directory.Exists(targetPath)) continue;
                try
                {
                    foreach (var file in Directory.GetFiles(targetPath, extension, SearchOption.TopDirectoryOnly))
                    {
                        try { FileInfo fi = new(file); freed += fi.Length; fi.Delete(); } catch { }
                    }
                }
                catch { }
            }
            return freed;
        }
    }
}